name: generate pacman game

on:
  schedule: # Run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # Allows manual triggering
  push: # Runs on every push to the main branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
      
      - name: Apply custom colors
        run: |
          # 벚꽃색 적용 (RGB: 255, 192, 203 또는 #FFC0CB)
          find dist -name "*.svg" -type f -exec sed -i 's/#c6e48b/#ffc0cb/g' {} \;
          find dist -name "*.svg" -type f -exec sed -i 's/#7bc96f/#ff9eb5/g' {} \;
          find dist -name "*.svg" -type f -exec sed -i 's/#239a3b/#ff7fa3/g' {} \;
          find dist -name "*.svg" -type f -exec sed -i 's/#196127/#ff608a/g' {} \;

      # Push the generated SVG to the output branch
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

